import { CH, type DeckApi } from "./ipc";

/** How the web app may reach each DeckApi member. A member added to DeckApi without an entry here fails remoteDeck.test.ts. */
export type Access =
  | { kind: "remote"; ch: string; mode: "invoke" | "send" }
  | { kind: "event"; ch: string; perId?: boolean }
  | { kind: "local" }
  | { kind: "blocked" };

const invoke = (ch: string): Access => ({ kind: "remote", ch, mode: "invoke" });
const send = (ch: string): Access => ({ kind: "remote", ch, mode: "send" });
const local: Access = { kind: "local" };
const blocked: Access = { kind: "blocked" };

export const DECK_ACCESS: Record<keyof DeckApi, Access> = {
  platform: local,
  home: local,
  getState: invoke(CH.getState),
  watchStop: blocked,
  accountSignIn: blocked,
  accountCancel: blocked,
  accountReopen: blocked,
  accountUseCode: blocked,
  accountProviders: blocked,
  accountEmail: blocked,
  accountSignOut: blocked,
  accountManage: blocked,
  onState: { kind: "event", ch: CH.state },
  onFocusSession: { kind: "event", ch: CH.focusSession },
  onShowNeedsYou: { kind: "event", ch: CH.showNeedsYou },
  onShowInboxItem: { kind: "event", ch: CH.showInboxItem },
  approve: invoke(CH.approve),
  reject: invoke(CH.reject),
  draftAssign: blocked,
  setSprint: blocked,
  ticketMemory: blocked,
  shellPrepare: blocked,
  issueBody: blocked,
  prSummary: blocked,
  startHere: blocked,
  sendText: invoke(CH.sendText),
  answerMenu: invoke(CH.answerMenu),
  inboxAct: invoke(CH.inboxAct),
  queueList: invoke(CH.queueList),
  queueEdit: invoke(CH.queueEdit),
  queueSendNext: invoke(CH.queueSendNext),
  getSettings: blocked,
  setSettings: blocked,
  onAutoOpen: blocked,
  setStatus: invoke(CH.setStatus),
  standupCommits: blocked,
  janitor: blocked,
  removeWorktree: blocked,
  removeSession: blocked,
  searchHistory: blocked,
  historyTranscript: blocked,
  templates: invoke(CH.templates),
  saveTemplate: blocked,
  deleteTemplate: blocked,
  ticketCreate: blocked,
  ticketBuilderPrepare: blocked,
  onTicketsCreated: blocked,
  ticketRepoMeta: blocked,
  workspaceRepos: invoke(CH.workspaceRepos),
  startClaude: invoke(CH.startClaude),
  resumeSession: invoke(CH.resumeSession),
  resumeStopped: invoke(CH.resumeStopped),
  tokensByDay: blocked,
  dismissStopped: invoke(CH.dismissStopped),
  assignIssue: blocked,
  assign: blocked,
  defaultModel: invoke(CH.defaultModel),
  refresh: blocked,
  refreshBoard: blocked,
  refreshTeamPrs: blocked,
  setupCheck: blocked,
  setupTool: blocked,
  ghAccounts: blocked,
  ghSwitch: blocked,
  ghOwners: blocked,
  configDetect: blocked,
  configDetectAll: blocked,
  configSave: blocked,
  pickFolder: blocked,
  hooksInstall: blocked,
  skillReinstall: blocked,
  skillRemove: blocked,
  workflowGet: blocked,
  workflowSave: blocked,
  workflowTemplateSave: blocked,
  workflowTemplateDelete: blocked,
  workflowBuilderPrepare: blocked,
  workflowDraftGet: blocked,
  onWorkflowDraft: blocked,
  workflowDraftDiscard: blocked,
  workflowDraftApply: blocked,
  workflowTriggerDelete: blocked,
  workflowStatus: blocked,
  sessionWorkflowGet: blocked,
  sessionWorkflowSave: blocked,
  summaryGet: blocked,
  summaryMake: blocked,
  summaryPost: blocked,
  linkSession: invoke(CH.linkSession),
  setBoardOpen: local,
  setFocus: local,
  setVisible: local,
  openExternal: local,
  openEditor: blocked,
  copy: local,
  stopSession: invoke(CH.stopSession),
  stopOtherSession: invoke(CH.stopOtherSession),
  stopSessions: invoke(CH.stopSessions),
  setManualStatus: invoke(CH.setManualStatus),
  statuslineInstall: blocked,
  statuslineUninstall: blocked,
  masterStart: invoke(CH.masterStart),
  ptyOpen: invoke(CH.ptyOpen),
  ptyWrite: send(CH.ptyWrite),
  ptyResize: send(CH.ptyResize),
  ptyClose: send(CH.ptyClose),
  onPtyData: { kind: "event", ch: CH.ptyData, perId: true },
  onPtyExit: { kind: "event", ch: CH.ptyExit, perId: true },
};

/** Event method name -> channel prefix (per-id events are `${prefix}:${id}`). */
export const REMOTE_EVENTS: Record<string, string> = {
  onState: CH.state,
  onFocusSession: CH.focusSession,
  onShowNeedsYou: CH.showNeedsYou,
  onShowInboxItem: CH.showInboxItem,
  onPtyData: CH.ptyData,
  onPtyExit: CH.ptyExit,
};

/** Argument reshaping the preload does for remote methods, so RemoteDeck and the preload agree. */
export const ARG_FIX: Partial<Record<keyof DeckApi, (args: unknown[]) => unknown[]>> = {
  inboxAct: ([id, a, p]) => [id, a, p ?? {}],
};
