import { CH, type DeckApi } from "./ipc";

/** How the web app may reach each DeckApi member. A member added to DeckApi without an entry here fails remoteDeck.test.ts. */
export type Access =
  | { kind: "remote"; ch: string; mode: "invoke" | "send" }
  | { kind: "event"; ch: string; perId?: boolean }
  | { kind: "local" }
  | { kind: "blocked" };

const invoke = (ch: string): Access => ({ kind: "remote", ch, mode: "invoke" });
const send = (ch: string): Access => ({ kind: "remote", ch, mode: "send" });
const local: Access = { kind: "local" };
const blocked: Access = { kind: "blocked" };

export const DECK_ACCESS: Record<keyof DeckApi, Access> = {
  platform: local,
  home: local,
  getState: invoke(CH.getState),
  watchStop: invoke(CH.watchStop),
  accountSignIn: blocked,
  accountCancel: blocked,
  accountReopen: blocked,
  accountUseCode: blocked,
  accountProviders: blocked,
  accountEmail: blocked,
  accountSignOut: blocked,
  accountManage: blocked,
  browserDecide: blocked,
  browserRevoke: blocked,
  onState: { kind: "event", ch: CH.state },
  onFocusSession: { kind: "event", ch: CH.focusSession },
  onShowNeedsYou: { kind: "event", ch: CH.showNeedsYou },
  onShowInboxItem: { kind: "event", ch: CH.showInboxItem },
  approve: invoke(CH.approve),
  reject: invoke(CH.reject),
  draftAssign: invoke(CH.draftAssign),
  setSprint: send(CH.setSprint),
  ticketMemory: invoke(CH.ticketMemory),
  shellPrepare: blocked,
  issueBody: invoke(CH.issueBody),
  prSummary: invoke(CH.prSummary),
  startHere: invoke(CH.startHere),
  sendText: invoke(CH.sendText),
  answerMenu: invoke(CH.answerMenu),
  inboxAct: invoke(CH.inboxAct),
  queueList: invoke(CH.queueList),
  queueEdit: invoke(CH.queueEdit),
  queueSendNext: invoke(CH.queueSendNext),
  getSettings: invoke(CH.getSettings),
  setSettings: invoke(CH.setSettings),
  onAutoOpen: blocked,
  onGhLogin: blocked,
  // Claude Code's trust prompt is answered on the Mac, in a tab of its window.
  trust: blocked,
  openClaudeIn: blocked,
  onOpenClaude: blocked,
  setStatus: invoke(CH.setStatus),
  standupCommits: invoke(CH.standupCommits),
  janitor: invoke(CH.janitor),
  removeWorktree: invoke(CH.removeWorktree),
  removeSession: invoke(CH.removeSession),
  searchHistory: invoke(CH.searchHistory),
  historyTranscript: invoke(CH.historyTranscript),
  templates: invoke(CH.templates),
  saveTemplate: invoke(CH.saveTemplate),
  deleteTemplate: invoke(CH.deleteTemplate),
  // Notes travel to a browser over the encrypted bridge only; they are in no snapshot.
  notesList: invoke(CH.notesList),
  notesGet: invoke(CH.notesGet),
  notesSearch: invoke(CH.notesSearch),
  notesSave: invoke(CH.notesSave),
  notesDelete: invoke(CH.notesDelete),
  onNotesChanged: { kind: "event", ch: CH.notesChanged },
  ticketCreate: invoke(CH.ticketCreate),
  ticketBuilderPrepare: invoke(CH.ticketBuilderPrepare),
  onTicketsCreated: { kind: "event", ch: CH.ticketsCreated },
  ticketRepoMeta: invoke(CH.ticketRepoMeta),
  workspaceRepos: invoke(CH.workspaceRepos),
  startClaude: invoke(CH.startClaude),
  resumeSession: invoke(CH.resumeSession),
  accountFor: invoke(CH.accountFor),
  resumeStopped: invoke(CH.resumeStopped),
  tokensByDay: invoke(CH.tokensByDay),
  dismissStopped: invoke(CH.dismissStopped),
  assignIssue: invoke(CH.assignIssue),
  assignableUsers: invoke(CH.assignableUsers),
  assign: invoke(CH.assign),
  defaultModel: invoke(CH.defaultModel),
  refresh: invoke(CH.refresh),
  refreshBoard: invoke(CH.boardRefresh),
  refreshTeamPrs: invoke(CH.teamPrsRefresh),
  setupCheck: invoke(CH.setupCheck),
  setupTool: invoke(CH.setupTool),
  ghAccounts: blocked,
  ghUser: blocked,
  ghOwners: blocked,
  configDetect: invoke(CH.configDetect),
  configDetectAll: invoke(CH.configDetectAll),
  configSave: invoke(CH.configSave),
  pickFolder: blocked,
  skillReinstall: invoke(CH.skillReinstall),
  skillRemove: invoke(CH.skillRemove),
  workflowGet: invoke(CH.workflowGet),
  workflowSave: invoke(CH.workflowSave),
  workflowTemplateSave: invoke(CH.workflowTemplateSave),
  workflowTemplateDelete: invoke(CH.workflowTemplateDelete),
  workflowBuilderPrepare: invoke(CH.workflowBuilderPrepare),
  workflowDraftGet: invoke(CH.workflowDraftGet),
  onWorkflowDraft: { kind: "event", ch: CH.workflowDraft },
  workflowDraftDiscard: invoke(CH.workflowDraftDiscard),
  workflowDraftApply: invoke(CH.workflowDraftApply),
  workflowTriggerDelete: invoke(CH.workflowTriggerDelete),
  workflowStatus: invoke(CH.workflowStatus),
  sessionWorkflowGet: invoke(CH.sessionWorkflowGet),
  sessionWorkflowSave: invoke(CH.sessionWorkflowSave),
  summaryGet: invoke(CH.summaryGet),
  summaryMake: invoke(CH.summaryMake),
  summaryPost: invoke(CH.summaryPost),
  linkSession: invoke(CH.linkSession),
  setBoardOpen: local,
  boardRepos: send(CH.boardRepos),
  boardCreatePlan: blocked,
  boardCreate: blocked,
  boardCreateRetry: blocked,
  onBoardCreateProgress: blocked,
  setFocus: local,
  setVisible: local,
  openExternal: local,
  openEditor: blocked,
  copy: local,
  stopSession: invoke(CH.stopSession),
  stopOtherSession: invoke(CH.stopOtherSession),
  stopSessions: invoke(CH.stopSessions),
  setManualStatus: invoke(CH.setManualStatus),
  statuslineInstall: invoke(CH.statuslineInstall),
  statuslineUninstall: invoke(CH.statuslineUninstall),
  masterStart: invoke(CH.masterStart),
  ptyOpen: invoke(CH.ptyOpen),
  ptyWrite: send(CH.ptyWrite),
  ptyResize: send(CH.ptyResize),
  ptyClose: send(CH.ptyClose),
  onPtyData: { kind: "event", ch: CH.ptyData, perId: true },
  onPtyExit: { kind: "event", ch: CH.ptyExit, perId: true },
};

/** Event method name -> channel prefix (per-id events are `${prefix}:${id}`). */
export const REMOTE_EVENTS: Record<string, string> = {
  onState: CH.state,
  onFocusSession: CH.focusSession,
  onShowNeedsYou: CH.showNeedsYou,
  onShowInboxItem: CH.showInboxItem,
  onPtyData: CH.ptyData,
  onPtyExit: CH.ptyExit,
  onWorkflowDraft: CH.workflowDraft,
  onTicketsCreated: CH.ticketsCreated,
  onNotesChanged: CH.notesChanged,
};

/** Argument reshaping the preload does for remote methods, so RemoteDeck and the preload agree. */
export const ARG_FIX: Partial<Record<keyof DeckApi, (args: unknown[]) => unknown[]>> = {
  inboxAct: ([id, a, p]) => [id, a, p ?? {}],
  sessionWorkflowSave: ([sid, steps, from]) => [sid, steps, from ?? null],
};
